[ethereum]
  URL = "ws://eth-tx.test.keep.network:8546"
  URLRPC = "http://eth-tx.test.keep.network:8545"

  [ethereum.account]
    Address = "0x48f4bb2cf7379467c3052cb8c5d9e3892eeda487"
    KeyFile = "/mnt/keep-client/config/eth-account-keyfile"

  # Contracts are already deployed to the private testnet.  They are subject to change on deployment
  [ethereum.ContractAddresses]
    KeepRandomBeaconOperator = "0x1Fa95B8B3Fb5706bf7f4cfD090fefcF66C370d48"
    TokenStaking = "0x7faB5e80690c188cd1E6ad4AcE93309C118f51e0"
    KeepRandomBeaconService = "0xc7836096D29036916Ee34f4721ce39937e37C481"

# We can configure multiple bootstrap peers.  For the purpose of initial testing we're keeping it at one.
[LibP2P]
  Peers = ["/dns4/bootstrap.test.keep.network/tcp/3919/ipfs/16Uiu2HAm9RGTm8VGne5PvZGAw9KYNDggHaEQh5wiGSKgibp2G95r"]
  Port = 3919
  NAT = false

# In the real world this directory should be on persistent storage.
[Storage]
  DataDir = "/mnt/keep-client/persistence"
