apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: eth-tx
  namespace: ropsten
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  replication-type: none
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate
