apiVersion: v1
kind: Service
metadata:
  name: eth-miner-p2p-tcp
  namespace: ropsten
  labels:
    app: geth
    type: miner
spec:
  type: LoadBalancer
  loadBalancerIP: 35.238.26.96
  ports:
  - name: tcp-p2p-30303
    port: 30303
    targetPort: 30303
  selector:
    app: geth
    type: miner
