apiVersion: v1
kind: Service
metadata:
  name: eth-tx-p2p-udp
  namespace: ropsten
  labels:
    app: geth
    type: tx
spec:
  type: LoadBalancer
  loadBalancerIP: 35.193.141.192
  ports:
  - name: udp-p2p-30303
    port: 30303
    targetPort: 30303
    protocol: UDP
  selector:
    app: geth
    type: tx
