apiVersion: v1
kind: Service
metadata:
  name: eth-tx
  namespace: ropsten
  labels:
    app: geth
    type: tx
spec:
  ports:
  - port: 8545
    targetPort: 8545
    name: tcp-rpc-8545
  - port: 8546
    targetPort: 8546
    name: tcp-ws-8546
  - port: 30303
    targetPort: 30303
    name: tcp-p2p-30303
  - port: 30303
    targetPort: 30303
    name: udp-p2p-30303
    protocol: UDP
  selector:
    app: geth
    type: tx
