apiVersion: v1
kind: Service
metadata:
  name: tenderly-agent
  namespace: default
  labels:
    app: tenderly
    type: agent
spec:
  type: LoadBalancer
  ports:
  - name: agent-port
    port: 8555
    targetPort: 8555
  selector:
    app: tenderly
    type: agent
