---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tenderly-agent
  labels:
    app: tenderly
    type: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenderly
      type: agent
  template:
    metadata:
      labels:
        app: tenderly
        type: agent
    spec:
      containers:
      - name: tenderly-agent
        image: gcr.io/tenderly-public/tenderly-agent:latest
        volumeMounts:
          - name: tenderly-agent-config
            mountPath: /tenderly/config
          - name: tenderly-agent-cert
            mountPath: /tenderly/.tenderly/cert
          - name: tenderly-agent-cert-key
            mountPath: /tenderly/.tenderly/private
      volumes:
        - name: tenderly-agent-config
          configMap:
            name: tenderly-agent
            items:
              - key: config.yaml
                path: config.yaml
        - name: tenderly-agent-cert
          configMap:
            name: tenderly-agent
            items:
              - key: tenderly-agent.crt
                path: tenderly-agent.crt
        - name: tenderly-agent-cert-key
          secret:
            secretName: tenderly-agent
            items:
              - key: tenderly-agent.key
                path: tenderly-agent.key