[ethereum]
  URL = "ws://eth-tx.test.keep.network:8546"
  URLRPC = "http://eth-tx.test.keep.network:8545"

  [ethereum.account]
    Address = "0x4902de99499ee74159779c0d92dd163bf689daf0"
    KeyFile = "/mnt/keep-client/config/eth-account-keyfile"

  # Contracts are already deployed to the private testnet.  They are subject to change on deployment
  [ethereum.ContractAddresses]
    KeepRandomBeaconOperator = "0x1Fa95B8B3Fb5706bf7f4cfD090fefcF66C370d48"
    TokenStaking = "0x7faB5e80690c188cd1E6ad4AcE93309C118f51e0"
    KeepRandomBeaconService = "0xc7836096D29036916Ee34f4721ce39937e37C481"

# We can configure multiple bootstrap peers.  For the purpose of initial testing we're keeping it at one.
[LibP2P]
  Peers = ["/dns4/bootstrap.test.keep.network/tcp/3919/ipfs/16Uiu2HAm9RGTm8VGne5PvZGAw9KYNDggHaEQh5wiGSKgibp2G95r"]
  Port = 3919
  # AnnouncedAddresses:
  # Leaving AnnouncedAddresses empty will set a default address to be
  # announced to the network.  The default address will vary by deploy
  # conditions.  Set AnnouncedAddresses if you have known external IPs
  # or DNS entries you want to route traffic through.
  AnnouncedAddresses = []

# In the real world this directory should be on persistent storage.
[Storage]
  DataDir = "/mnt/keep-client/persistence"
